
require "bexx.options"
require "bexx.keymaps"
require "bexx.plugins"
require "bexx.colorscheme"
require "bexx.cmp"
require "bexx.lsp"
require "bexx.telescope"
require "bexx.treesitter"
require "bexx.autopairs"
require "bexx.comment"
require "bexx.gitsigns"
require "bexx.bufferline"
require "bexx.toggleterm"
require "bexx.project"
-- require "bexx.impatient"
require "bexx.indentline"
-- require "bexx.alpha"
require "bexx.whichkey"
require "bexx.autocommands"
require "bexx.airline"
